### ISSUE TITLE
Client crashes, server hangs while staring

### ISSUE THREAD

**Issue by defnull** [AllOfFabric/All-of-Fabric-2#36]
After I tried to use the wooden excavator for the first time, the client crashed and the server won't restart.

Client error:

```
---- Minecraft Crash Report ----
// But it works on my machine.

Time: 2020-06-24 15:33:15 CEST
Description: Tesselating block in world - Indigo Renderer

java.lang.ClassCastException: net.minecraft.class_853 cannot be cast to net.minecraft.class_1937
    at Not Enough Crashes deobfuscated stack trace.(1.15.2+build.17)
    at alexiil.mc.lib.multipart.impl.MultipartBlock.getOutlineShape(MultipartBlock.java:130)
    at net.minecraft.block.BlockState.getOutlineShape(BlockState:208)
    at net.minecraft.block.BlockState.getOutlineShape(BlockState:204)
    at net.minecraft.block.Block.isTranslucent(Block:539)
    at net.minecraft.block.BlockState.isTranslucent(BlockState:90)
    at net.minecraft.block.Block.getOpacity(Block:548)
    at net.minecraft.block.BlockState.getOpacity(BlockState:97)
    at net.fabricmc.fabric.impl.client.indigo.renderer.aocalc.AoCalculator.computeFace(AoCalculator.java:411)
    at net.fabricmc.fabric.impl.client.indigo.renderer.aocalc.AoCalculator.vanillaFullFace(AoCalculator.java:232)
    at net.fabricmc.fabric.impl.client.indigo.renderer.aocalc.AoCalculator.calcFastVanilla(AoCalculator.java:208)
    at net.fabricmc.fabric.impl.client.indigo.renderer.aocalc.AoCalculator.compute(AoCalculator.java:142)
    at net.fabricmc.fabric.impl.client.indigo.renderer.render.TerrainFallbackConsumer.renderQuad(TerrainFallbackConsumer.java:143)
    at net.fabricmc.fabric.impl.client.indigo.renderer.render.TerrainFallbackConsumer.accept(TerrainFallbackConsumer.java:98)
    at net.fabricmc.fabric.impl.client.indigo.renderer.render.TerrainFallbackConsumer.accept(TerrainFallbackConsumer.java:61)
    at net.minecraft.client.render.model.BakedModel.emitBlockQuads(BakedModel:1045)
    at net.fabricmc.fabric.impl.client.indigo.renderer.render.TerrainRenderContext.tesselateBlock(TerrainRenderContext.java:105)
    at net.minecraft.client.render.chunk.ChunkBuilder$BuiltChunk$RebuildTask.redirect$zzp000$hookChunkBuildTesselate(ChunkBuilder:711)
    at net.minecraft.client.render.chunk.ChunkBuilder$BuiltChunk$RebuildTask.render(ChunkBuilder:512)
    at net.minecraft.client.render.chunk.ChunkBuilder$BuiltChunk$RebuildTask.run(ChunkBuilder:434)
    at net.minecraft.client.render.chunk.ChunkBuilder$BuiltChunk.rebuild(ChunkBuilder:399)
    at net.minecraft.client.render.chunk.ChunkBuilder.rebuild(ChunkBuilder:181)
    at net.minecraft.client.render.WorldRenderer.setupTerrain(WorldRenderer:919)
    at net.minecraft.client.render.WorldRenderer.render(WorldRenderer:1089)
    at net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer:718)
    at net.minecraft.client.render.GameRenderer.render(GameRenderer:543)
    at net.minecraft.client.MinecraftClient.render(MinecraftClient:989)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:619)
    at net.minecraft.client.main.Main.main(Main:204)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
    at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
    at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at link.infra.jumploader.Jumploader.onLoad(Jumploader.java:164)
    at cpw.mods.modlauncher.TransformationServiceDecorator.onLoad(TransformationServiceDecorator.java:53)
    at cpw.mods.modlauncher.TransformationServicesHandler.lambda$loadTransformationServices$11(TransformationServicesHandler.java:131)
    at java.util.HashMap$Values.forEach(HashMap.java:981)
    at cpw.mods.modlauncher.TransformationServicesHandler.loadTransformationServices(TransformationServicesHandler.java:131)
    at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:56)
    at cpw.mods.modlauncher.Launcher.run(Launcher.java:75)
    at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
    at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:39)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
    at org.multimc.EntryPoint.listen(EntryPoint.java:143)
    at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Block being tesselated --
  Block: Block{minecraft:grass_block}[snowy=false]
  Block location: World: (-253,71,-227), Chunk: (at 3,4,13 in -16,-15; contains blocks -256,0,-240 to -241,255,-225), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)

-- Affected level --
  All players: 1 total; [class_746['Junoka'/56626, l='MpServer', x=-251.75, y=73.00, z=-227.51]]
  Chunk stats: Client Chunk Cache: 729, 529
  Level dimension: minecraft:overworld
  Level name: MpServer
  Level seed: 5351828749704856177
  Level generator: ID 00 - default, ver 1. Features enabled: false
  Level generator options: {}
  Level spawn location: World: (-192,67,-256), Chunk: (at 0,4,0 in -12,-16; contains blocks -192,0,-256 to -177,255,-241), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
  Level time: 1493286 game time, 1160931 day time
  Known server brands: 
  Level was modded: false
  Level storage version: 0x00000 - Unknown?
  Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
  Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
  Server brand: fabric
  Server type: Non-integrated multiplayer server

-- System Details --
  Minecraft Version: 1.15.2
  Minecraft Version ID: 1.15.2
  Operating System: Linux (amd64) version 5.3.0-59-generic
  Java Version: 1.8.0_242, AdoptOpenJDK
  Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), AdoptOpenJDK
  Memory: 1145348336 bytes (1092 MB) / 3517448192 bytes (3354 MB) up to 5607784448 bytes (5348 MB)
  CPUs: 4
  JVM Flags: 2 total; -Xms512m -Xmx6016m
  Suspected Mods: Fabric Loader (fabricloader), Fabric Renderer - Indigo (fabric-renderer-indigo), LibMultiPart (libmultipart), Jumploader (jumploader)
  Fabric Mods: adabraniummod: Adabranium Mod 1.1.3-1.15.2
               adorn: Adorn 1.8.4+1.15.2
               advancements-enlarger: Advancements Enlarger 1.0.0
               amecs: Amecs 1.2.9+1.15-pre5
               appleskin: AppleSkin 1.0.8
               aquarius: Aquarius 1.4.0+1.15
               archcreatia: Arch Creatia 0.9.0
               artifice: Artifice 0.6.1+1.15.2
               artis: Artis 1.2.0+1.15.2
               ash_clay: AshClay 1.0.0
               autoconfig1u: Auto Config v1 Updated 2.2.0
               autorun: Auto-Run 0.2.0
               azuma: Azuma 1.2.6
               bambootweaks: Bamboo Tweaks 1.15.2-1.1.6
               beachslimes: Beach Slimes 2.0.0+mc1.15.2
               bebooks: Better Enchanted Books 1.15.2-1.0.1
               beeangry-est: Bee Angry-est 1.4.0+1.15.1
               beebetter: Bee Better 1.6.0
               beecompatible: Bee Compatible 2.0.0+1.15.1
               beeproductive: Bee Productive 1.0.2+1.15.1
               beeresourceful: Bee Resourceful 1.15.1-0.2.1
               better-world-list: Better World List 1.0.0-1.15.2
               better_wither_skeletons: Better Wither Skeletons 1.0.0
               bettermineshafts: YUNG's Better Mineshafts 0.4.1
               biow0rks: biow0rk5 0.4.51
               blast: BLAST 1.1.1
               blockus: Blockus 1.5.3-1.15.2
               blue_endless_jankson: jankson +
               bootz: BootZ 1.2
               boringbackgrounds: Boring Backgrounds 2.1.0-1.15.2
               bulkyshulkies: Bulky Shulkies 1.0.7
               bunch-o-trinkets: Bunch O' Trinkets 1.0.0
               campanion: Campanion 1.0.11+build.21
               cardinal-components-base: Cardinal Components API 2.3.5
               cardinal-components-entity: Cardinal Components API 2.3.5
               cardinal-components-item: Cardinal Components API 2.3.6
               cardinal-components-world: Cardinal Components API 2.3.4
               cavebiomes: Cave Biomes 0.2.2
               chainmail: Chainmail 0.1.0
               chestlatchfixer: ChestLatchFixer 1.1.0
               chunkborders: ChunkBorders 0.4.2
               chunkpregen: Fabric Chunk Pregenerator 0.2.0
               claybucket: Clay Bucket 1.0.0
               cleardespawn: Clear Despawn 1.0.4
               clipboards: Clipboards 1.0.0+1.15.2
               cloth: Cloth Events 1.2.0
               cloth-basic-math: Cloth Basic Math 0.5.0
               cloth-config2: Cloth Config v2 2.14.1
               cmdkeybind: Command Macros 1.4.2
               coderecipes: Programmatic Recipes 0.2.3
               coloredcampfire: Colorful Campfire Smoke 1.1.3
               com_github_h0tk3y_betterparse_better-parse-jvm: better-parse-jvm 0.4.0-alpha-3
               com_github_kilianb_pcg-java-8: pcg-java-8 1.0.1
               com_moandjiezana_toml_toml4j: toml4j 0.7.2
               com_typesafe_config: config 1.3.1
               composing: Composing 1.0.2+1.15.2
               compostrecipes: Compost Recipes 1.1.0
               compressedblocks: Compressed Blocks 0.3
               connected_block_textures: Connected Block Textures 0.1.0
               conveyance: Conveyance 0.3.3+1.15.2
               cornflower: Cornflower 1.2.3+fabric.1.15.2
               cotton: Cotton 1.0.3
               cotton-cauldron: Cotton Cauldron 1.0.3
               cotton-commons: Cotton Commons 1.0.0-rc.4
               cotton-config: Cotton Config 1.0.0-rc.7
               cotton-datapack: Cotton Datapack 1.0.1
               cotton-logging: Cotton Logging 1.0.0-rc.4
               cotton-player-events: Cotton Player Events 1.0.2
               couplings: Couplings 1.3.1
               craftingpad: Crafting Pad 1.0.4
               craftpresence: CraftPresence 1.6.1
               creativebuttonmover: Creative Button Mover 0.1.2
               creeperspores: Creeper Spores 1.3.7
               crimsonmoon: Crimson Moon 1.0.0
               cursedearth: Cursed Earth 1.0
               customtitlescreen: CustomTitleScreen 1.15.2-0.1.1
               cwt: Climatic World Type 1.1.4
               dark-loading-screen: Dark Loading Screen 1.2.2
               dataloader: Data Loader 2.0.0+mc1.15.2
               diggusmaximus: Diggus Maximus 1.2.10
               dynagear: DynaGear 1.3.4+1.15.2
               dynocaps: DynoCaps 1.0.7
               eggtab: Egg Tab 1.1.2+1.15-1.16
               enchantedtooltips: Enchanted ToolTips 1.3.0
               enderbox: Ender Box 1.0.1
               exotic-blocks: Exotic Blocks 1.2.112
               exotic-matter: Exotic Matter 1.18.299
               expandedstorage: ExpandedStorage 5.0.1
               extraalchemy: Extra Alchemy 1.0.3
               extradoors: ExtraDoors 1.8.0-1.15
               extrashields: Extra Shields 0.2.0+1.15.2
               fabric: Fabric API 0.12.0+build.313-1.15
               fabric-api-base: Fabric API Base 0.1.2+b7f9825d95
               fabric-biomes-v1: Fabric Biomes (v1) 0.1.5+3b05f68e0c
               fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8975
               fabric-climbable-api-v1: Fabric Climbable API (v1) 1.0.0+6ffe71e20c
               fabric-command-api-v1: Fabric Command API (v1) 1.0.2+2aebb7ff0c
               fabric-commands-v0: Fabric Commands (v0) 0.2.0+2e0c4ff50c
               fabric-containers-v0: Fabric Containers (v0) 0.1.3+b7f9825d0c
               fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.3+b7f9825d0c
               fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d0c
               fabric-diagonal-panes: Fabric Diagonal Panes 0.2.1
               fabric-dimensions-v1: fabric-dimensions-v1 0.3.0+2ad156310c
               fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.0+fac69e320c
               fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.1.2+003643510c
               fabric-furnaces: Fabric Furnaces 1.2.0
               fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+0121bd900c
               fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.0+2af3af910c
               fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+2af3af910c
               fabric-language-kotlin: Fabric Language Kotlin 1.3.71+build.1
               fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.5+e08a73050c
               fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+ec951ea40c
               fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d60c
               fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.3+e08a73050c
               fabric-networking-v0: Fabric Networking (v0) 0.1.7+12515ed90c
               fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.2.1+e7a4edb30c
               fabric-object-builders-v0: Fabric Object Builders (v0) 0.5.1+3e5587510c
               fabric-particles-v1: fabric-particles-v1 0.1.2+ad2f81bd0c
               fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.2.6+f3d8141b0c
               fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.10+f08b61330c
               fabric-renderer-indigo: Fabric Renderer - Indigo 0.2.23+9290e2ed0c
               fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a600c
               fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d0c
               fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.6+12515ed90c
               fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+534104900c
               fabric-rendering-v1: Fabric Rendering (v1) 1.0.0+2a034f0a0c
               fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.1.10+06c939b375
               fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.1.3+abd915800c
               fabric-textures-v0: Fabric Textures (v0) 1.0.4+821cdba70c
               fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.1.0+3e5587510c
               fabricdrawer: Fabric Drawer 3.2.0-1.15-pre1
               fabricloader: Fabric Loader 0.8.7+build.201
               facility: Facility 0.7.118
               fairenchanting: FairEnchanting 1.1.2
               fatxporbs: Fat Experience Orbs 0.0.6
               fermion: Fermion 1.14.154
               fermion-gui: Fermion GUI 1.5.154
               fermion-modkeys: Fermion Modifier Keys 1.5.148
               fermion-simulator: Fermion Simulator 1.4.154
               fermion-varia: Fermion Varia 1.12.154
               fiber: fiber 0.22.1-2
               flax: Flax 1.1.1
               flonters: Flonters 1.0.2+1.15.1
               floradoubling: Flora Doubling 1.15.2-20w06a-1.0.0
               fluidity: Fluidity 0.9.160
               fonthack: Font Hack 1.1.17
               frex: FREX 1.3.102
               ftc: Fabric Title Changer 1.0.2
               gameinfo: GameInfo 1.3.5 1.15.2
               gamemodeoverhaul: GamemodeOverhaul 1.15.1-1.0.1.6
               giftit: Gift It! 1.1.2+1.15-pre7
               givemehats: Give Me Hats! 1.0.0
               glassdoor: Glass Doors 1.4.3
               glassential: Glassential 1.15.1-1.1.3
               globedimension: Chunk In A Globe 1.15.2-1.0.2
               glowingbeds: Glowing Beds 1.0.2
               godown: Go Down 0.2.0+1.15
               goml: Get Off My Lawn 1.0.0-beta
               grass_kiss: Grass Kiss 0.2.2
               greenstone: Greenstone Circuits 0.0.2
               hardcorequesting: Hardcore Questing Mode 0.1.2-SNAPSHOT
               hctm-base: HCTM Base 2.0.2
               healthoverlay: Health Overlay 2.3.10
               hollowlogs: Hollow Logs 1.0.0
               horizontal-glass-panes: Horizontal Glass Panes 1.0.0
               horsestatsvanilla: Horse Stats Vanilla 1.0.5
               i-need-keybinds: I Need Keybinds 0.2.1-unstable.201912010804
               iamverysmart: I Am Very Smart 2.0.0+mc1.15.2
               imbuedtorches: Imbued Torches 1.1.0
               improved-stations: Improved Stations 1.2.5
               infinityfix: Infinity Fix 1.1.0
               inmis: Inmis 2.1.2-beta
               inventorysorter: Inventory Sorter 1.6.4
               irishwolves: Irish Wolves 1.0.0
               iron-jetpacks: Iron Jetpacks 0.1.2-SNAPSHOT
               ironbarrels2: Iron Barrels 2 2.3.0
               itemmagnets: Item Magnets 1.0.0
               jankson: Jankson 2.0.1+j1.2.0
               joml-mod: JOML Mod 1.4.13
               jumploader: Jumploader 1.0.7
               jumpoverfences: JumpOverFences 1.16-snapshot-0.0.2
               justmap: Just Map 1.0.73
               kayak: kayak 0.1.1.22
               kyrptconfig: Kytpt Config 1.0.1
               lakeside: Lakeside 1.0.0+1.15.2
               libaddict: libaddict 0.1.2
               libblockattributes: LibBlockAttributes 0.6.6
               libblockattributes_core: LibBlockAttributes (Core) 0.6.6
               libblockattributes_fluids: LibBlockAttributes (Fluids) 0.6.6
               libblockattributes_items: LibBlockAttributes (Items) 0.6.6
               libcd: LibCapableData 2.4.1+1.15.2
               libgamerule: LibGamerule ${version}
               libgui: LibGui 1.10.0+1.15.2
               libmultipart: LibMultiPart 0.3.6
               libmultipart_deps_container: LibMultiPart (Dependency Container) 0.3.6
               libnetworkstack: Lib Network Stack 0.3.6
               lightoverlay: Light Overlay 4.6.1
               linkart: Linkart 1.3.2+fabric-1.15.2
               linkedstorage: Linked Storage 1.3.1
               lithium: Lithium 0.4.6
               llamasteeds: Llama Steeds 2020.2.8
               loadcatcher: Entrypoint Catcher 1.1.0
               lootstrap: Lootstrap 1.0.0
               ltr: LilTaterReloaded 1.0.5+1.15.2
               lvmnt: SuperAxes 1.0.5
               malilib: MaLiLib 0.10.0-dev.21+arne.2
               materialisation: Materialisation 2.6
               mcmarkdown: MC Markdown 1.1.620
               me_shedaniel_cloth_basic-math: basic-math 0.3.0
               me_zeroeightsix_fiber: fiber 0.12.0-5
               minecraft: Minecraft 1.15.2
               missingbits: Missing Bits v1.15.2 Fabric b1
               ml3api: ML3API 1.3.3
               mm: Manningham Mills 2.0
               mo_glass: Mo Glass 1.2-MC1.15.2
               mobjar: mob.jar 1.0.1+1.15.2
               mobropes: Mob Ropes 1.15.2+1.0.2
               modmenu: Mod Menu 1.10.2+build.32
               mooblooms: Mooblooms 1.1.1
               moreberries: More Berries 1.2.3
               moretotems: More Totems 2.4
               mostructures: Mo' Structures 0.1.2+mc.1.15
               mousewheelie: Mouse Wheelie 1.4.13+mc1.15.2
               ninjaphenix-container-lib: NinjaPhenix's Container Library 0.1.6
               notenoughcrashes: Not Enough Crashes 1.2.2+1.15.1
               okzoomer: Ok Zoomer 2.1.4-1.15.2
               orderly: Orderly 2.0.0-alpha+build.7-1.15
               org_apache_httpcomponents_httpclient: httpclient 4.5.10
               org_apache_httpcomponents_httpcore: httpcore 4.4.12
               org_apache_httpcomponents_httpmime: httpmime 4.5.10
               org_jetbrains_annotations: annotations 19.0.0
               org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.3.71
               org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.3.71
               org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.3.71
               org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.3.71
               org_jetbrains_kotlinx_kotlinx-coroutines-core: kotlinx-coroutines-core 1.3.5
               org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.5
               org_jetbrains_kotlinx_kotlinx-serialization-runtime: kotlinx-serialization-runtime 0.14.0
               org_spongepowered_configurate-core: configurate-core 3.6
               org_spongepowered_configurate-hocon: configurate-hocon 3.6
               oysters: Oysters fabric-0.1.5-1.15.2
               oysterscooking: Oysters Cooking 0.2.3b
               patchouli: Patchouli 1.15.2-1.2-34-FABRIC
               phosphor: Phosphor 0.5.2+build.6
               playerabilitylib: Pal 1.1.0
               pling: Pling 1.1.1
               pocketplants: Pocket Plants 1.0.2
               programmerartinjector: Programmer Art Injector 1.1.2
               qcommon-cfg-core: qcommon-cfg-core 2.0.1
               qcommon-croco: Croco 1.0.5
               quickshulker: Quick Shulker 1.1.4
               reach-entity-attributes: Reach Entity Attribute 1.0.0
               reborncore: Reborn Core 4.2.9+build.115
               redstonebits: Redstone Bits 1.2.2
               retroexchange: Retro Exchange 1.0.0
               riverredux: RiverRedux 0.1.1
               rotmgfood: Rotmg Food 1.1.0
               roughlyenoughitems: Roughly Enough Items 3.6.21
               roughlyenoughresources: Roughly Enough Resources 1.3.2
               rswires: RSWires 4.0.6
               rtree-3i-lite-fabric: rtree-3i-lite for Fabric 0.3.0
               sandwichable: Sandwichable 1.1.1
               satin: Satin 1.4.0-nightly.19w46b+build.1
               screenshotclipboard: Screenshot to Clipboard 1.0.5
               secretrooms: Secret Rooms 0.5.4
               sheet-lib: SheetLib 1.7.0+1.15.2
               shest: Shest 1.3.4+fabric-1.15.2
               shulkerboxtooltip: Shulker Box Tootip 2.0.3+1.15.2
               shulkercharm: Shulker Charm 1.1.2+1.15.2
               simpledrawers: Simple Drawers 1.7.2
               simpleteleporters: Simple Teleporters 2.2.0
               simplevoidworld: Simple Void World 1.0.0
               simplexterrain: Simplex Terrain 0.5.1
               skin_change: Minecraft Skin Change Mod 1.0.0
               skyworld: SkyWorld 0.4.1-pre-release
               sneakthroughberries: Sneak Through Berries 1.15.2-20w06a-1.0.1
               sneakyscreens: Sneaky Screens 1.0.1
               soulbound: Soulbound 1.0.1
               soulshards: Soul Shards Respawn 1.2.0
               special-circumstances: Special Circumstances 1.4.154
               spelunkers: Spelunker's Treasures 1.0.0
               spinnery: Spinnery 2.0.28+fabric-1.15.2
               staticdata: Static Data 1.1.2
               step-height-entity-attribute: Step Height Entity Attribute 1.0.0
               strongandfairanvils: Strong and Fair Anvils 0.3.0+1.15
               survivalisland: Survival Island 0.1.0
               sweed: Sweed 1.1.1
               sweettooth: Sweet Tooth 1.1.2
               swordeffects: Sword Effect 1.1.1
               tacocraft: TacoCraft 1.2.3+mc.1.15
               team_reborn_energy: Energy 0.1.0
               techreborn: Tech Reborn 3.3.11+build.224
               terraform: Terraform 1.5.5+build.39
               terrestria: Terrestria 1.2.1+build.29
               thehallow: The Hallow 1.1.4-beta+1.15.2
               tinyconfig: TinyConfig 1.1.2
               tinyfuel: Tiny Fuel 0.2.1
               tippy: Tippy 1.1.2
               tk_valoeghese_zoesteriaconfig: ZoesteriaConfig 1.2.0
               tooltipped: Tooltipped 1.1
               tooltipwrap: Tooltip Autowrap 1.0.2
               tradesmen: Wandering Tradesmen 1.1.3
               trapexpansion: Trap Expansion 1.3.1
               traverse: Traverse 2.1.14+build.37
               trinkets: Trinkets 2.4.2
               trumpet-skeleton: Trumpet Skeleton 1.1.1
               tweed: Tweed API 2.2.9
               universalcomponents: Universal Components 0.7.1+1.15.2
               vanilla-hammers: Vanilla Hammers 1.7.0
               vanilla-toolsets: Vanilla Toolsets 1.2.2
               vanilla_parts: Vanilla Parts 1.1.2+1.15.1
               vanillaexcavators: Vanilla Excavators 1.1.0
               verticalredstone: Vertical Redstone 1.1.0
               villagerhats: Villager Hats fabric-1.15.0-1.0.0
               waila: Hwyla 1.9.22
               wands: Wands Mod 1.0.9
               whereisit: Where Is It 1.5
               wildworld: Wild World 1.2.0+1.15
               winged: Winged Mod 1.15-1.0
               winwonders: Window Wonders 0.1.2
               wolveswitharmor: Wolves With Armor 1.1.0
               working-scheduler: Working Scheduler 1.1.3-1.15-pre1
               worldtraveler: World Traveler 1.0.5
               wrenchable: Wrenchable 0.2.2+1.15.2
               yet_another_gravestone_mod: Yet Another Gravestone Mod 1.2.2
               yosbr: YOSBR 0.1.1
  Patchouli open book context: n/a
  Launched Version: MultiMC5
  Backend library: LWJGL version 3.2.2 build 10
  Backend API: AMD PITCAIRN (DRM 2.50.0, 5.3.0-59-generic, LLVM 9.0.0) GL version 4.5 (Compatibility Profile) Mesa 19.2.8, X.Org
  GL Caps: Using framebuffer using OpenGL 3.0
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fabric'
  Type: Client (map_client.txt)
  Resource Packs: 
  Current Language: English (US)
  CPU: 4x Intel(R) Core(TM) i5 CPU 750 @ 2.67GHz
  Client Crashes Since Restart: 1
  Integrated Server Crashes Since Restart: 0

```

Server hangs while preparing spawn area:
```
[15:50:34] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[15:50:38] [Server thread/INFO]: Preparing spawn area: 0%
[15:50:38] [Server thread/INFO]: Preparing spawn area: 0%
[15:50:38] [Server thread/INFO]: Preparing spawn area: 0%
[15:50:38] [Server thread/INFO]: Preparing spawn area: 0%
[15:50:38] [Server thread/INFO]: Preparing spawn area: 0%
[15:50:38] [Server thread/INFO]: Preparing spawn area: 0%
[15:50:38] [Server thread/INFO]: Preparing spawn area: 0%
[15:50:38] [Server thread/INFO]: Preparing spawn area: 0%
[15:50:38] [Server thread/INFO]: Preparing spawn area: 0%
[15:50:39] [Server-Worker-4/INFO]: Preparing spawn area: 54%
```

**Comment by defnull** [comment]
Found out that this may is the issue for the server not starting: https://github.com/TechReborn/TechReborn/issues/2128
Startup hangs in `techreborn.blockentity.generator.SolarPanelBlockEntity.updatePanel(SolarPanelBlockEntity.java:79)` but the hang is caused by a different mod.

**Comment by defnull** [comment]
Updating to `Expanded Storage 5.1.2+1.15.2` fixes the server issue
